### ISSUE TITLE
Fail to run

### ISSUE THREAD

**Issue by fyodef** [foozzi/bitcoin-fork-checker#2]
Traceback (most recent call last):
  File "main.py", line 112, in <module>
    Fork(args.filepath, args.threads)
  File "main.py", line 16, in __init__
    with Pool(int(threads)) as p:
AttributeError: __exit__

What is the issue? I've tried to run but failed. I did install all the exact requirements

Thanks sir

**Comment by foozzi** [comment]
Are you sure that you run on python3? what os?

**Comment by Vladimir855** [comment]
![image](https://user-images.githubusercontent.com/48643229/77243377-6a80d900-6c1a-11ea-8a18-f307f58a9e2a.png)

**Comment by Vladimir855** [comment]
python 3.8, win7 все обновлено
может другой напишешь чекер

**Comment by su314ka** [comment]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Python37\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "D:\Downloads\bitcoin-fork-checker-master\main.py", line 51, in make_all
    bch = self.bch_balance(address)
  File "D:\Downloads\bitcoin-fork-checker-master\main.py", line 63, in bch_balance
    balance = r.json()['balance']
  File "C:\Python37\lib\site-packages\requests\models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 113, in <module>
    Fork(args.filepath, args.threads)
  File "main.py", line 17, in __init__
    p.map(self.make_all, f)
  File "C:\Python37\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Python37\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by foozzi** [comment]
@Vladimir855 если это актуально я могу переписать
